version: '3.8'
services:
    transcription-api:
        container_name: transcription-api
        platform: linux/x86_64 # Critical so Prisma runs correctly on a M1 Mac
        build: ./
        command: 'tail -f /dev/null'
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://audio_transcription_user:slo0Umbj5PSn58dxcfX10s3t+pir5baitUPMljtskZQ=@transcription-db:5432/transcription?schema=public
            - HOST=0.0.0.0
            - PORT=5501
        ports:
            - 5501:5501
            - 9240:5500 # Node inspect
        volumes:
            - ./:/home/app/api
            - node_modules:/home/app/api/node_modules
        working_dir: /home/app/api
        restart: on-failure
        depends_on:
            - transcription-db
        networks:
            - default

    transcription-db:
        container_name: transcription-db
        image: postgres
        environment:
            - POSTGRES_USER=audio_transcription_user
            - POSTGRES_DB=transcription
            - POSTGRES_PASSWORD=slo0Umbj5PSn58dxcfX10s3t+pir5baitUPMljtskZQ=
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGDATA=/var/lib/postgresql/data/pgdata # Critical for Postgres to work in the container
        volumes:
            - ./db/data/postgres:/var/lib/postgresql
        ports:
            - 5502:5432

networks:
    default:

volumes:
    node_modules:
