#!/bin/bash

 . scripts/utils/docker_helpers
 . scripts/utils/colors

echo ""
yellow 'Starting server...'
blue 'Server is port forwarded to localhost even though it says the host is 0.0.0.0'
echo ""

run-in-transcription-api 'npm run server'

echo ""
green 'Server stopped!'




