#!/bin/bash

 . scripts/utils/colors
 . scripts/utils/bash_helpers

yellow 'Building and tagging container transcription:$(git_revision)'
docker build --platform=linux/amd64 -t transcription:$(git_revision) .
docker tag transcription:$(git_revision) transcription:latest



# gcloud auth configure-docker us-central1-docker.pkg.dev
# docker login https://us-central1-docker.pkg.dev
# docker tag firebox us-central1-docker.pkg.dev/allboarder-public/app-containers/firebox:latest
# docker push us-central1-docker.pkg.dev/allboarder-public/app-containers/firebox:latest
