#!/bin/bash

# Secrets file was created with:
# secret_key=$1
# secret_value=$2
# encoded_file=infrastructure/production/secrets/$secret_key.encoded.yml
# encrypted_file=infrastructure/production/secrets/$secret_key.encrypted.yml

# # Create an unencrypted kubernetes secret
# kubectl create secret generic $secret_key \
#           --from-literal $secret_key=$secret_value \
#           -o yaml \
#           --dry-run=client > $encoded_file

# # Create an encrypted kubernetes secret from the unencrypted kubernetes secret
# sops --encrypt --encrypted-regex '^(data|stringData)$' $encoded_file > $encrypted_file

editor=$1 || "code"

EDITOR="$editor --wait" sops infrastructure/production/secrets/secrets.encrypted.yml
