#!/bin/bash

# Get a single pod, we dont care which if there are multiple
pod=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n firebox | head -n 1)
kubectl exec $pod -n firebox -- npm run data-migration
